name: "Feature Request"
description: Suggest a new feature for the app
labels: [ enhancement, untriaged ]
body:

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've already searched in [existing issues](https://github.com/Ashinch/ReadYou/issues?q=is%3Aissue+) and haven't found a similar feature request.
          required: true


  - type: dropdown
    id: types
    attributes:
      label: Which category best fits this feature request?
      options:
        - Feed Sync & Management
        - User Interface
        - Integration with other apps
        - Others
    validations:
      required: true


  - type: textarea
    id: description_1
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description:
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: description_2
    attributes:
      label: Describe the solution you'd like
      description:
      placeholder: A clear and concise description of what you want to do in the app.
    validations:
      required: false
  - type: textarea
    id: description_3
    attributes:
      label: Related links
      description:
      placeholder: Please provide links to the feed or article where this feature might be beneficial.
    validations:
      required: false